### PR TITLE
Give up with OpenGraph images for now.

### PR DESCRIPTION
**Pull request by Lukas1h**
Can't use dynamic OpenGraph images due to Vercel using the deployment URL, which is locked behind Vercel auth, instead of the site URL for OpenGraph images. See this issue for more: https://github.com/vercel/vercel/issues/9968.

### CODE REVIEW

**Comment by gmonte** [comment]
I am using next 14.1.0 and I have the same issue

**Comment by Lukas1h** [comment]
> I am using next 14.1.0 and I have the same issue

Yeah it really sucks. 😕

Let me know if you find a solution. I'd really appreciate it.

**Comment by clevertree** [comment]
Same issue v13.5.5-canary.16

**Comment by clevertree** [comment]
I found a fix which is working for me. Just make it an absolute url, and vercel doesn't rewrite it. Annoying, but can be managed with env variables
image
until they fix their product. good luck!

**Comment by Lukas1h** [comment]
> I found a fix which is working for me. Just make it an absolute url, and vercel doesn't rewrite it. Annoying, but can be managed with env variables

Bro you're my hero. Thanks a ton!

**Pull request merged**
